### ISSUE TITLE
php artisan vendor:publish --tag=laravel-bible

### ISSUE THREAD

**Issue by joelelangovan1985** [djunehor/laravel-bible#1]
/Hi, when i run publish, I get an error "Can't locate path: <../vendor/djunehor/laravel-bible/src/config/laravel-bible.php>". And the other files ,2019_11_22_145649_create_words_table.php.stub,LaravelBibleSeeder.php.stub,entries.csv.zip. I am using the latest laravel 8. Seems like you have not added the files to github. can you please look into it ?

**Comment by djunehor** [comment]
Hi,
Thank you for reporting the bug. The issue has been resolved. You don't need to run an extra step (publish command) after installing the package.  Do let me know how I can be of further help
